

GET http://127.0.0.1:60610/api/usuarios
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjYwNjEwL2FwaS9sb2dpbiIsImlhdCI6MTc3MTgxMDU3MCwiZXhwIjoxNzcxODE0MTcwLCJuYmYiOjE3NzE4MTA1NzAsImp0aSI6Ik5Fc2plejE2UDZxVDJqSmUiLCJzdWIiOiIyIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.ZiqcxDRMlq2mh_JnveN11UxgmkNyJYv_71utT4YfEYA

###
GET http://127.0.0.1:80/api/logout
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xL2FwaS9sb2dpbiIsImlhdCI6MTc3MTcxMDg5MiwiZXhwIjoxNzcxNzE0NDkyLCJuYmYiOjE3NzE3MTA4OTIsImp0aSI6ImZMT1BEMDlYb3VsVlNoTkMiLCJzdWIiOiIyIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.hjIjVeechORFFfe1vAY1C6zcBP6BXhMsJcXtC89UZzk
###
###

DELETE  http://127.0.0.1:80/api/usuarios/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU4NzkwL2FwaS9sb2dpbiIsImlhdCI6MTc3MTcyMDIxNSwiZXhwIjoxNzcxNzIzODE1LCJuYmYiOjE3NzE3MjAyMTUsImp0aSI6IjZKc3JFUDE5b1lCY0pSOUQiLCJzdWIiOiI1IiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.aha7JivGTg-dJVQCA7RZiWtBODDCfWXVeuG1n2o73nE


###
PATCH   http://127.0.0.1:80/api/usuarios/2 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Leo Joshua Orellana Molina",
    "email": "bryanfuentesm.54@gmail.com",
    "role": "empleado",
    "password": "bryanfuentes23"
}















###
POST http://127.0.0.1:60610/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "alladsadasfgk3@gmail.com",
    "password": "admin12345"
}

###
POST http://127.0.0.1:60610/api/registro HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Usuario Admin falso",
    "email": "alladsadasfgk3@gmail.com",
    "role": "",
    "password": "admin12345"
}